config/routes.rb
Scoreboard::Application.routes.draw do
  root to: 'boards#index'

  post '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', as: :signout
  
  resources :boards
  resources :users do
    member do
      get :accept_terms
    end
  end
  resources :tasks do
    collection do
      post :complete, action: "complete_by_encrypted_package"
    end

    member do
      post :solve
      get :complete, action: "complete_by_signature"
    end
  end

  get '/credits', to: 'credits#index'
  get '/tutorial', to: 'tutorial#index'
  get '/rules', to: 'rules#index'
  get '/terms_and_conditions', to: 'rules#terms_and_conditions'
  
  namespace :admin do
    resources :tasks do
      collection {post :sort}
    end
    resources :scores do
      member do
        put :approve
        put :deny
      end
      collection do
        get :recalculate_scores
        get :remove_duplicates
      end
    end
    resources :users do
      member do
        get :tasks
        get :history
        put :freeze
        put :unfreeze
        post :award_points
        post :complete_task
      end
    end
    get '/reports', to: 'reports#index'
    get '/reports/task_completion', to: 'reports#task_completion'
    get '/reports/task_details', to: 'reports#task_details'
    get '/reports/player_timelines', to: 'reports#player_timelines'
    get '/reports/player_details', to: 'reports#player_details'
    get '/reports/points_awarded', to: 'reports#points_awarded'
    get '/reports/unique_logins', to: 'reports#unique_logins'
    get '/reports/mailing_list', to: 'reports#mailing_list'
    post '/tutorial/change', to: 'tutorial#change'
  end

  get "/:page", to: "static#show", as: "static"
end

app/models/task.rb
require 'digest/hmac'
require 'encryptor'

class Task < ActiveRecord::Base
  CATEGORIES = %w(BeThere SolveThis GetSchooled FindSomeone PlayTheBook)
  
  has_many :scores, dependent: :destroy
  has_many :users, through: :scores
  
  acts_as_list
  attr_accessible :name, :description, :value, :starts_on, :ends_on, :category, :milestone, :pyramid, :bonus, :solution, :icon, :feedback

  validates_presence_of :name, :description, :value, :category, allow_blank: false
  validates_presence_of :bonus, :icon, if: :milestone?
  validates_inclusion_of :category, in: CATEGORIES

  scope :active, where("(starts_on IS NULL OR starts_on <= ?) AND (ends_on IS NULL OR ends_on >= ?)", Date.today, Date.today)
  mount_uploader :icon, MilestoneIconUploader

  before_validation :generate_token

  def active?
    !upcoming? && !expired?
  end

  def upcoming?
    starts_on? && Date.today < starts_on
  end

  def expired?
    ends_on? && Date.today > ends_on
  end

  def complete!(user)
    points = self.value
    points += self.bonus if milestone? && scores.count < 10
    score = Score.new({task: self, user: user, points: points, day: Date.today, approved: !user.freeze_points?}, as: :admin)
  end

  def to_param
    "#{id}-#{name.underscore.gsub(" ","-").gsub(/[^a-z0-9-]/i,"")}"
  end

  def signature
    Digest::HMAC.hexdigest(id.to_s, "--#{Rails.application.config.secret_token}--ready?", Digest::SHA1)
  end

  def encrypted_package_for(user)
    Encryptor.encrypt [token, user.id].join(",")
  end

  def generate_token
    self.token ||= SecureRandom.hex(20)
  end
end

app/controllers/admin/tasks_controller.rb
class Admin::TasksController < ApplicationController
  layout "admin"
  
  before_filter :login_required, :admin_required
  before_filter :find_task, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @tasks = Task.order(:position).all
    respond_with @tasks
  end
  
  def sort
    params[:task].each_with_index do |id, index|
      Task.update_all({position: index+1}, {id: id})
    end
    render nothing: true
  end

  def create
    @task = Task.new(params[:task])
    if @task.save
      redirect_to admin_tasks_path, notice: "Task '#{@task.name}' created successfully."
    else
      flash.now[:alert] = "There was a problem creating the task"
      render action: :new
    end
  end

  def new
    @task = Task.new
  end

  def update
    if @task.update_attributes(params[:task])
      redirect_to admin_tasks_path, notice: "Updated task successfully."
    else
      flash.now[:alert] = "There was a problem updating the task. Check below."
      render action: :edit
    end
  end

  def destroy
    if @task.destroy
      redirect_to admin_tasks_path, notice: "Successfully deleted task '#{@task.name}'"
    else
      redirect_to admin_tasks_path, alert: "There was a problem deleting task '#{@task.name}'"
    end
  end

  protected

  def find_task
    @task = Task.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
require 'encryptor'

class TasksController < ApplicationController
  before_filter :login_required, except: [:complete_by_encrypted_package]
  before_filter :acceptance_required, except: [:complete_by_encrypted_package]
  before_filter :find_task, only: [:show, :solve]

  def index
    @tasks = Task.active.order(:position).all
  end

  def solve
    @task = Task.find(params[:id])
    
    unless @task.solution.downcase.split("|").include? params[:solution].downcase
      redirect_to task_path(@task), alert: "Your solution was incorrect" and return
    end
    
    @score = @task.complete!(current_user)
    if @score.save
      flash[:cryptic] = @task.feedback unless @task.feedback.blank?
      redirect_to user_path(current_user), notice: "Congratulations! You received #{@score.points} points for completing the '#{@task.name}' task."
    else
      redirect_to task_path(@task), alert: @score.errors[:base].join('\n')
    end
  end

  def complete_by_signature
    @task = Task.find(params[:id])

    unless @task.signature == params[:signature]
      redirect_to user_path(current_user), alert: "The QR signature URL you supplied was invalid." and return
    end

    @score = @task.complete!(current_user)
    if @score.save
      redirect_to user_path(current_user), notice: "Congratulations! You received #{@score.points} points for completing the '#{@task.name} task by QR code."
    else
      redirect_to user_path(current_user), alert: "Encountered a problem while trying to complete task by QR Code."
    end
  end

  def complete_by_encrypted_package
    task_token, user_id = *Encryptor.decrypt(params[:package]).split(",")

    @task = Task.find_by_token!(task_token)
    @user = User.find_by_id!(user_id)

    score = @task.complete!(@user)
    if score.save
      render text: "Awarded #{score.points} points to #{@user.name} for completing '#{@task.name}'"
    else
      render text: "There was a problem with the encrypted package [#{score.errors[:base].join(',')}], could not complete task."
    end
  end

  protected

  def find_task
    @task = Task.find(params[:id])
  end
end

app/helpers/admin/tasks_helper.rb
module Admin::TasksHelper
  def all_tasks_chart_data
    first_completion_at = Score.order("created_at").first().try(:created_at) || 3.weeks.ago
    first_completion_at -= 1.day
    tasks_by_day = Score.group("date(scores.created_at)").count()
    data = (first_completion_at.to_date..Date.today).map do |date|
      {
        date: date,
        count: tasks_by_day[date.to_s] || 0
      }
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admin/tasks/_form.html.erb
<div class="row">
  <div class="span4">
    <%= f.input :name %>
    <%= f.input :category, as: 'select', collection: Task::CATEGORIES %>
    <%= f.input :value, label: "Point Value" %>
    <%= f.input :description, input_html: {rows: 5} %>
  </div>
  <div class="span4">
    <%= f.input :starts_on, as: 'date_picker', label: "Start Date" %>
    <%= f.input :ends_on, as: 'date_picker', label: "End Date" %>
    <%= f.input :pyramid, wrapper: :checkbox, as: :boolean, label: "Pyramid Task?" %>
    <p class="help-block">Increases by 10 points each completion</p>
    <%= f.input :milestone, wrapper: :checkbox, as: :boolean, label: "Milestone Task?" %>
    <%= f.input :bonus, label: "Milestone Bonus Points" %>
    <%= f.input :icon, label: "Icon Image", as: :file %>
    <%= image_tag(@task.icon.url) if @task && @task.icon? %>
  </div>
  <div class="span4">
    <%= f.input :solution, hint: "The correct answer for this task's form-based task completion.", input_html: {rows: 5} %>
    <%= f.input :feedback, hint: "A message to be displayed at task completion.", input_html: {rows: 5} %>
  </div>
</div>

app/views/admin/tasks/edit.html.erb
<h1 class="page-header">
  <%= link_to "&laquo; Back to Tasks".html_safe, admin_tasks_path, class: "btn pull-right" %>
  Editing Task '<%= @task.name %>'
</h1>

<%= simple_form_for @task, url: admin_task_path(@task) do |f| %>
  <%= render "admin/tasks/form", f: f %>
  <div class="form-actions">
    <button type="submit" class="btn btn-primary">Update Task</button>
    <input type="reset" class="btn" value="Reset"> 
  </div>
<% end %>

app/views/admin/tasks/index.html.erb
<h1 class="page-header">
  <%= link_to "New Task", new_admin_task_path, class: "pull-right btn btn-primary" %>
  Task Admin
</h1>
<% if @tasks.any? %>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Points</th>
      <th>URLs</th>
      <th>Token</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody id="sortable-tasks" data-update-url="<%= sort_admin_tasks_url %>">
    <% @tasks.each do |task| %>
    <%= content_tag_for :tr, task do %>
      <th class="drag-handle">
        <% if task.milestone? %>
          <i class='icon icon-flag'></i> 
        <% end %>
        <%= task.name %>
      </th>
      <td><%= task.value %></td>
      <td>
        <%= content_tag :div, "Solve Link/QR", data:{ url: task_url(task)}, class: 'btn btn-primary btn-small popup-trigger' %>
        <%= content_tag :div, "Autocomplete Link/QR", data:{ url: complete_task_url(task, signature: task.signature)}, class: 'btn btn-primary btn-small popup-trigger' %>
      </td>
      <td><code><%= task.token %></code></td>
      <td><%= truncate task.description %></td>
      <td>
        <%= link_to "Edit", edit_admin_task_path(task), class: 'btn btn-small btn-success' %>
        <%= link_to "Delete", admin_task_path(task), class: 'btn btn-small btn-danger', confirm: "Are you sure you want to delete this task?", method: :delete %>
      </td>
    <% end %>
    <% end %>
  </tbody>
</table>
<p>Drag tasks by thier name to re-order</p>
<% else %>
<p class='lead'>No tasks have been created. <%= link_to "Create a new one?", new_admin_task_path %></p>
<% end %>

<div id="linkModal" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3></h3>
  </div>
  <div class="modal-body">
  </div>
  <div class="modal-footer">
    <button type="button" data-dismiss="modal">Done</button>
  </div>
</div>

app/views/admin/tasks/new.html.erb
<h1 class="page-header">Create a New Task</h1>

<%= simple_form_for @task, url: admin_tasks_path do |f| %>
  <%= render "admin/tasks/form", f: f %>
  <div class="form-actions">
    <button type="submit" class="btn btn-primary">Create Task</button>
    <input type="reset" class="btn" value="Reset"> 
  </div>
<% end %>