config/routes.rb
Scoreboard::Application.routes.draw do
  root to: 'boards#index'

  post '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', as: :signout
  
  resources :boards
  resources :users do
    member do
      get :accept_terms
    end
  end
  resources :tasks do
    collection do
      post :complete, action: "complete_by_encrypted_package"
    end

    member do
      post :solve
      get :complete, action: "complete_by_signature"
    end
  end

  get '/credits', to: 'credits#index'
  get '/tutorial', to: 'tutorial#index'
  get '/rules', to: 'rules#index'
  get '/terms_and_conditions', to: 'rules#terms_and_conditions'
  
  namespace :admin do
    resources :tasks do
      collection {post :sort}
    end
    resources :scores do
      member do
        put :approve
        put :deny
      end
      collection do
        get :recalculate_scores
        get :remove_duplicates
      end
    end
    resources :users do
      member do
        get :tasks
        get :history
        put :freeze
        put :unfreeze
        post :award_points
        post :complete_task
      end
    end
    get '/reports', to: 'reports#index'
    get '/reports/task_completion', to: 'reports#task_completion'
    get '/reports/task_details', to: 'reports#task_details'
    get '/reports/player_timelines', to: 'reports#player_timelines'
    get '/reports/player_details', to: 'reports#player_details'
    get '/reports/points_awarded', to: 'reports#points_awarded'
    get '/reports/unique_logins', to: 'reports#unique_logins'
    get '/reports/mailing_list', to: 'reports#mailing_list'
    post '/tutorial/change', to: 'tutorial#change'
  end

  get "/:page", to: "static#show", as: "static"
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController
  layout "admin"
  before_filter :login_required, :admin_required

  def player_timelines
    @players = User.players 
  end

  def player_details
    @players = User.players
    render xlsx: "player_details", filename: "player_details_#{Date.today}"
  end

  def task_details
    @tasks = Task.all
    render xlsx: "task_details", filename: "task_details_#{Date.today}"
  end

  def mailing_list 
    emails = User.pluck(:eid).map{|eid| "#{eid}@k-state.edu"}
    send_data emails.join(', '), :filename => "rpo_maling_list.txt"
  end
  
end

app/views/admin/reports/index.html.erb
<h1 class="page-header">
 Administrative Reports
</h1>

<ul class="report-list">

  <li>
    <%= link_to "Unique Logins Report", admin_reports_unique_logins_path, class: "btn btn-info" %>
    Displays the number of unique participant logins by day.
  </li>

  <li>
    <%= link_to "Player Timelines Report", admin_reports_player_timelines_path, class: "btn btn-info" %>
    Displays timeline for individual players
  </li>

  <li>
    <%= link_to "Player Details Report", admin_reports_player_details_path, class: "btn btn-info" %>
    Displays detailed report for individual players, including join time and completion time for all tasks, in Excell workbook format
  </li>
  
  <li>
    <%= link_to "Task Completion Report", admin_reports_task_completion_path, class: "btn btn-info" %>
    Displays the number of tasks completed by day by all participants in the game.
  </li>

  <li>
    <%= link_to "Task Details Report", admin_reports_task_details_path, class: "btn btn-info" %>
    Detailed report of task completion, including who completed each task when, in Excel workbook format.
  </li>

  <li>
    <%= link_to "Points Awarded Report", admin_reports_points_awarded_path, class: "btn btn-info" %>
    Displays the total number of points completed by day by all participants in the game.
  </li>

  <li>
    <%= link_to "Download Maling List", admin_reports_mailing_list_path, class: "btn btn-info" %>
    Provides a list of email addresses as a text file.
  </li>
  
</div>

app/views/admin/reports/player_details.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
<% @players.each do |player| %>
  <Worksheet ss:Name="<%= player.eid %> Details">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Details for <%= player.name %> (<%= player.eid %>)</Data></Cell>
      </Row>
      <Row>
        <Cell><Data ss:Type="String">Time</Data></Cell>
        <Cell><Data ss:Type="String">Event</Data></Cell>
      </Row>
      <Row>
        <Cell><Data ss:Type="Date"><%= player.created_at %></Data></Cell>
        <Cell><Data ss:Type="String">Joined the Game</Data></Cell>
      </Row>
    <% player.scores.order(:created_at).each do |score| %>
      <Row>
        <Cell><Data ss:Type="Date"><%= score.created_at %></Data></Cell>
        <Cell><Data ss:Type="String">Completed <%= score.task.name %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
<% end %>
</Workbook>

app/views/admin/reports/player_timelines.html.erb
<h1 class="page-header">
<%= link_to "&laquo; Back to Reports".html_safe, admin_reports_path, class: "btn pull-right" %>
 Player Details
</h1>

<% @players.each do |player| %>
  <h3>
    <%= player.eid %>
    <%= " (#{player.name})" if player.eid != player.name %> 
  </h3>
  <%= content_tag :div, "", id: "timeline-#{player.id}", class: "timeline", data: { timeline: user_timeline_data(player) } %>
<% end %>

app/views/admin/reports/points_awarded.html.erb
<h1 class="page-header">
<%= link_to "&laquo; Back to Reports".html_safe, admin_reports_path, class: "btn pull-right" %>
 Total Points Scored by Day
</h1>

<%= content_tag :div, "", id: "scores_chart", data: {scores: scores_chart_data} %>

app/views/admin/reports/task_completion.html.erb
<h1 class="page-header">
 <%= link_to "&laquo; Back to Reports".html_safe, admin_reports_path, class: "btn pull-right" %>
 Task Completion Report
</h1>

<h2>Total Tasks Completed By All Students</h2>
<%= content_tag :div, "", class: "report-chart", id: "total_task_completion_chart", data: {task_completion: all_tasks_chart_data} %>

app/views/admin/reports/task_details.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Summary">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Completions</Data></Cell>
        <Cell><Data ss:Type="String">Completed By</Data></Cell>
      </Row>
    <% @tasks.each do |task| %>
      <Row>
        <Cell><Data ss:Type="String"><%= task.name %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= task.scores.count %></Data></Cell>
        <Cell><Data ss:Type="String"><%= task.users.collect(&:eid).join(", ") %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
<% @tasks.each do |task| %>
  <Worksheet ss:Name="<%= task.name %> Details">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Completed</Data></Cell>
        <Cell><Data ss:Type="String">EID</Data></Cell>
        <Cell><Data ss:Type="String">Username</Data></Cell>
      </Row>
    <% task.scores.order(:created_at).each do |score| %>
      <Row>
        <Cell><Data ss:Type="Date"><%= score.created_at %></Data></Cell>
        <Cell><Data ss:Type="String"><%= score.user.eid %></Data></Cell>
        <Cell><Data ss:Type="String"><%= score.user.name %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
<% end %>
</Workbook>

app/views/admin/reports/unique_logins.html.erb
<h1 class="page-header">
 <%= link_to "&laquo; Back to Reports".html_safe, admin_reports_path, class: "btn pull-right" %>
 Unique Logins Per Day
</h1>

<%= content_tag :div, "", class: "report-chart", id: "unique_logins_chart", data: {logins: logins_chart_data} %>