config/routes.rb
Scoreboard::Application.routes.draw do
  root to: 'boards#index'

  post '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', as: :signout
  
  resources :boards
  resources :users do
    member do
      get :accept_terms
    end
  end
  resources :tasks do
    collection do
      post :complete, action: "complete_by_encrypted_package"
    end

    member do
      post :solve
      get :complete, action: "complete_by_signature"
    end
  end

  get '/credits', to: 'credits#index'
  get '/tutorial', to: 'tutorial#index'
  get '/rules', to: 'rules#index'
  get '/terms_and_conditions', to: 'rules#terms_and_conditions'
  
  namespace :admin do
    resources :tasks do
      collection {post :sort}
    end
    resources :scores do
      member do
        put :approve
        put :deny
      end
      collection do
        get :recalculate_scores
        get :remove_duplicates
      end
    end
    resources :users do
      member do
        get :tasks
        get :history
        put :freeze
        put :unfreeze
        post :award_points
        post :complete_task
      end
    end
    get '/reports', to: 'reports#index'
    get '/reports/task_completion', to: 'reports#task_completion'
    get '/reports/task_details', to: 'reports#task_details'
    get '/reports/player_timelines', to: 'reports#player_timelines'
    get '/reports/player_details', to: 'reports#player_details'
    get '/reports/points_awarded', to: 'reports#points_awarded'
    get '/reports/unique_logins', to: 'reports#unique_logins'
    get '/reports/mailing_list', to: 'reports#mailing_list'
    post '/tutorial/change', to: 'tutorial#change'
  end

  get "/:page", to: "static#show", as: "static"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :scores, dependent: :destroy
  has_many :tasks, through: :scores
  has_many :admin_actions
  has_many :daily_pings

  validates_presence_of :eid, :name
  after_create :update_scores!

  scope :admins, where(admin: true)
  scope :players, where(admin: false).where(accepted_terms_and_conditions: true)
  
  def score(category = nil)
    return self[:score] unless category 
    self["score_#{category.underscore}"]
  end

  def milestones
    tasks.where(milestone: true)
  end

  def self.from_auth(auth_hash)
    user = find_by_eid(auth_hash.uid)
    return user if user

    user = User.new do |u|
      u.eid = auth_hash.uid
      u.name = auth_hash.uid # if provider has name, it can be used instead: auth["info"]["name"]
    end
    user.save!
    
    user
  end

  def completed?(task)
    tasks.where(id: task.id).any?
  end
  
  def incomplete_tasks
    complete_task_ids = tasks.collect{|t| t.id}
    Task.all.reject{|t| complete_task_ids.include? t.id}
  end

  def update_scores!
    self.score = scores.approved.sum(:points)
    Task::CATEGORIES.each do |category|
      self["score_#{category.underscore}"] = scores.in_category(category).approved.sum(:points)
    end
    self.save!
  end

  def to_param
    "#{id}-#{eid.underscore.gsub(" ","-").gsub(/[^a-z0-9-]/i,"")}"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'
  before_filter :login_required, :admin_required
  before_filter :find_user, only: [:history, :tasks, :freeze, :unfreeze, :award_points, :complete_task]

  def index
    if params[:filter] == "frozen"
      @users = User.where(freeze_points: true).all
    elsif params[:filter] == "points_modified"
      @users = User.includes(:scores).where("scores.admin_id IS NOT NULL").where("scores.task_id IS NULL").all
    elsif params[:filter] == "tasks_modified"
      @users = User.includes(:scores).where("scores.admin_id IS NOT NULL").where("scores.task_id IS NOT NULL").all
    elsif params[:filter] == "admins"
      @users = User.admins.all
    else
      @users = User.all
    end
  end
  
  def freeze
    @user.freeze_points = true
    if @user.save
      AdminAction.create(admin: current_user, user: @user, description: "Froze user")
      redirect_to history_admin_user_path(@user), notice: "User #{@user.name} frozen successfully."   
    else
      redirect_to history_admin_user_path(@user), alert: "User #{@user.name} could not be frozen."
    end
  end

  def unfreeze
    @user.freeze_points = false
    if @user.save
      AdminAction.create(admin: current_user, user: @user, description: "Unfroze user")
      redirect_to history_admin_user_path(@user), notice: "User #{@user.name} unfrozen successfully."
    else
      redirect_to history_admin_user_path(@user), alert: "User #{@user.name} could not be unfrozen."
    end
  end
  
  def history
    @admin_actions = @user.admin_actions.order("admin_actions.created_at")
  end
  
  def tasks
    @tasks = Task.all
  end

  def award_points
    @score = Score.new({user: @user, admin: current_user, points: params[:score][:points], approved: true}, as: :admin)
    @score.admin_override = true
    if @score.save
      AdminAction.create(admin: current_user, user: @score.user, description: "Awarded #{@score.points} points")
      redirect_to history_admin_user_path(@user), notice: "Awarded #{params[:score][:points]} points to #{@user.name}"
    else
      redirect_to history_admin_user_path(@user), alert: "Could not award #{params[:score][:points]} points to #{@user.name}"
    end
  end
  
  def complete_task
    @task = Task.find(params[:task])
    @score = @task.complete!(@user)
    @score.admin = current_user
    @score.admin_override = true
    if @score.save
      AdminAction.create(admin: current_user, user: @score.user, description: "Marked #{@score.task.name} as complete")
      redirect_to tasks_admin_user_path(@user), notice: "Completed task #{@task.name} for #{@user.name}, awarding #{@score.points} points"
    else
      redirect_to admin_users_path, alert: "Could not complete task #{@task.name} for #{@user.name} because #{@score.errors.full_messages.join(',')}"
    end
  end

  protected

  def find_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required
  before_filter :acceptance_required, except: :accept_terms
  
  def show
    @user = User.find(params[:id])
    unless current_user.admin? || @user == current_user
      redirect_to "/", alert: "You cannot access that player's profile page." and return
    end
    @user.update_scores!
    @milestones = @user.milestones.order("scores.created_at asc")
    @scores = @user.scores.includes(:task).order("scores.created_at asc") # .where("tasks.milestone = ?", false)
  end
  
  def edit
    @user = User.find(params[:id])
    unless current_user.admin? || @user == current_user
      redirect_to "/", alert: "You cannot change that player's handle." and return
    end
  end  
  
  def update
    @user = User.find(params[:id])
    unless current_user.admin? || @user == current_user
      redirect_to "/", alert: "You cannot change that player's handle." and return
    end
    
    name = params[:user][:name]
    if Blacklist.on_list? name
      redirect_to edit_user_path(@user), alert: "The name '#{name}' is inappropriate." and return
    end
    @user.name = name
    @user.save
    
    @milestones = @user.milestones.order("scores.created_at asc")
    @scores = @user.scores.includes(:task).order("scores.created_at asc") # .where("tasks.milestone = ?", false)
    render action: :show
  end  
  
  def accept_terms
    @user = User.find(params[:id])
    unless @user == current_user
      render "/rules/terms_and_conditions", alert: "You cannot accept terms and conditiosn for another player."
    end
    
    @user.accepted_terms_and_conditions = true
    @user.save
    redirect_to "/", notice: "Play on!"
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def user_timeline_data(user)
    data = [{
      start: user.created_at,
      content: "Joined the game"
    }]
    user.scores.each do |score|
      data << {
        start: score.created_at,
        content: score.task ? "Completed #{score.task.name} for #{score.points} points" : "Admin assigned #{score.points} points"
      }
    end
    data
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_actions.html.erb
<%= form_for Score.new, url: award_points_admin_user_path(user), html: {class: 'form-inline'} do |f| %>
  <%= f.text_field :points, class: "input-mini" %>
  <%= f.submit "Award Points", class: 'btn btn-small btn-success' %>
<% end %>

<% if user.freeze_points? %>
  <%= link_to "Unfreeze User", unfreeze_admin_user_path(user), method: :put, class: "btn btn-small btn-warning" %>
<% else %>
  <%= link_to "Freeze User", freeze_admin_user_path(user), method: :put, class: "btn btn-small btn-warning" %>
<% end %>

<%= link_to "History", history_admin_user_path(user), class: "btn btn-small btn-info" %>
<%= link_to "Tasks", tasks_admin_user_path(user), class: "btn btn-small btn-info" %>

app/views/admin/users/history.html.erb
<h1 class="page-header">Administrative History for <%= link_to @user.name, @user %></h1>

<div class="row">

  <div class="span8">
  
    <table class="table table-striped table-bordered admin-users-list">
      <thead>
        <tr>
          <th>Date</td>
          <th>Action Taken</th>
          <th>Responsible Admin</th>
        </tr>
      </thead>
      <tbody>
        <% @admin_actions.each do |action| %>
        <tr>
          <th><%= action.created_at %></th>
          <td><%= action.description %></td>
          <td><%= action.admin.name %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>
  
  <div class="span4">
    <%= render "admin/users/actions", user: @user %>
  </div>
  
</div>

app/views/admin/users/index.html.erb
<h1 class="page-header">User Admin</h1>

<ul class="nav nav-pills">
  <li<%=raw ' class="active"' unless params[:filter] %>><%= link_to "All Users", admin_users_path %></li>
  <li<%=raw ' class="active"' if params[:filter] == 'frozen' %>><%= link_to "Frozen", admin_users_path(filter: 'frozen') %></li>
  <li<%=raw ' class="active"' if params[:filter] == 'points_modified'%>><%= link_to "Points Modified", admin_users_path(filter: 'points_modified') %></li>
  <li<%=raw ' class="active"' if params[:filter] == 'tasks_modified'%>><%= link_to "Tasks Modified", admin_users_path(filter: 'tasks_modified') %></li>
  <li<%=raw ' class="active"' if params[:filter] == 'admins'%>><%= link_to "Admins", admin_users_path(filter: 'admins') %></li>
</ul>

<table class="table table-striped table-bordered admin-users-list">
  <thead>
    <tr>
      <th>EID</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <th><%= link_to user.name, user_path(user) %></th>
      <td><%= user.admin?? "Admin" : (user.freeze_points?? "Frozen" : "Normal") %></td>
      <td>
        <% unless user.admin? %>
          <%= render "admin/users/actions", user: user %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/tasks.html.erb
<h1 class="page-header">Tasks for <%= link_to @user.name, @user %></h1>

<div class="row">

  <div class="span8">
      
    <table class="table table-striped table-bordered admin-users-list">
      <thead>
        <tr>
          <th>Task</td>
          <th>Completed</th>
          <th>Points Awarded</th>
        </tr>
      </thead>
      <tbody>
        <% @tasks.each do |task| %>
        <% score = @user.scores.where(:task_id => task.id).first %>
          <tr>
            <th><%= link_to task.name, task %></th>
            <td><%= score ? score.updated_at : link_to( "Mark Complete", complete_task_admin_user_path(@user, task: task), method: :post, class: 'btn btn-danger btn-small' ) %></td>
            <td>
              <%= score.points if score %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  
  <div class="span4">
    <%= render "admin/users/actions", user: @user %>
  </div>
  
</div>