config/routes.rb
Scoreboard::Application.routes.draw do
  root to: 'boards#index'

  post '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', as: :signout
  
  resources :boards
  resources :users do
    member do
      get :accept_terms
    end
  end
  resources :tasks do
    collection do
      post :complete, action: "complete_by_encrypted_package"
    end

    member do
      post :solve
      get :complete, action: "complete_by_signature"
    end
  end

  get '/credits', to: 'credits#index'
  get '/tutorial', to: 'tutorial#index'
  get '/rules', to: 'rules#index'
  get '/terms_and_conditions', to: 'rules#terms_and_conditions'
  
  namespace :admin do
    resources :tasks do
      collection {post :sort}
    end
    resources :scores do
      member do
        put :approve
        put :deny
      end
      collection do
        get :recalculate_scores
        get :remove_duplicates
      end
    end
    resources :users do
      member do
        get :tasks
        get :history
        put :freeze
        put :unfreeze
        post :award_points
        post :complete_task
      end
    end
    get '/reports', to: 'reports#index'
    get '/reports/task_completion', to: 'reports#task_completion'
    get '/reports/task_details', to: 'reports#task_details'
    get '/reports/player_timelines', to: 'reports#player_timelines'
    get '/reports/player_details', to: 'reports#player_details'
    get '/reports/points_awarded', to: 'reports#points_awarded'
    get '/reports/unique_logins', to: 'reports#unique_logins'
    get '/reports/mailing_list', to: 'reports#mailing_list'
    post '/tutorial/change', to: 'tutorial#change'
  end

  get "/:page", to: "static#show", as: "static"
end

app/views/layouts/_flashes.html.erb
<% flash.keys.each do |type| %>
  
  <div class="alert alert-<%= alert_type(type) %>">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <span class="message"><%= flash[type] %></span>
  </div>
  
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ready Player One: The Game [Admin Mode]</title>
  <meta name="viewport" content="width=device-width, initial-scale=0.5">
  <link href='http://fonts.googleapis.com/css?family=Press+Start+2P|Play' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <a class="brand" href="/admin/tasks">Scoreboard <small class='text-danger'>Admin Mode</small></a>
        <button class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse" type="button">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="nav-collapse collapse">
          <ul class="nav">
            <li><%= link_to "Tasks", admin_tasks_path %></li>
            <li><%= link_to "Users", admin_users_path %></li>
            <li><%= link_to "Reports", admin_reports_path %></li>
          </ul>
          <ul class="nav pull-right">
            <li><%= link_to current_user.name, user_path(current_user) %></li>
            <li><%= link_to "Leave Admin Mode", root_path %></li>
            <li>
              <a href="/sign_out">Sign Out</a> 
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <%= render "layouts/flashes" %>
    <%= yield %>
  </div>
  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scoreboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=0.5">
  <link href='http://fonts.googleapis.com/css?family=Press+Start+2P|Play' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar">
    <div class="navbar-inner">
      <a class="brand" href="/">Scoreboard</a>
      <div class="container">  

        <button class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse" type="button">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <div class="nav-collapse collapse">

          <ul class="nav pull-left">
            <li><%= link_to "Leaderboards", boards_path %></li>
            <li><%= link_to "Tutorial", tutorial_path %></li>
            <li><%= link_to "Challenges", tasks_path %></li>
            <li><%= link_to "Rules", rules_path %></li>
            <li><%= link_to "Credits", credits_path %></li>
          </ul>

          <ul class="nav pull-right">
            <% if signed_in? %>
              <li>
                <%= link_to current_user.name, user_path(current_user) %>
              </li>
              <% if current_user.admin? %>
                <li><%= link_to "Enter Admin Mode", admin_tasks_path %></li>
              <% end %>
              <li>
                <a href="/sign_out">Sign Out</a> 
              </li>
            <% else %>
              <li><%= link_to "Sign In", "/auth/cas" %></li>
            <% end %>
          </ul>
        </div>

      </div>
    </div>
  </div>
  <div class="container">
    <%= render "layouts/flashes" %>
    <%= yield %>
  </div>
  <%= javascript_include_tag "application" %>
</body>
</html>